void LED_Enable();
void LED_Config();
void LED_Display();
void LED_GreenEnable(void);
void LED_Init(void);
void LED_Configure(void);
void LED_DisplayGreen(int val);
void LED_InitYellow(void);
void LED_DisplayYellow(int val);
void LED_Disp3LED(int pattern);
